### ISSUE TITLE
P4 - group radio buttons

### ISSUE THREAD

**Issue by ErrolKeith** [ErrolKeith/CornerTeam#10]
radio buttons on the panel are not functioning as radio buttons. Need to add all the radio buttons on the panel to a group object so only one can be selected at a time.

**Comment by savursool247** [comment]
Agreed. Which is why I made mine to use checkboxes. But that doesnt work either since only one action should be picked at a time

**Comment by savursool247** [comment]
Errol confirmed he'll work on this. It's low priority.

**Comment by ErrolKeith** [comment]
completed and commited to master
