### ISSUE TITLE
P4 - Decide the exact method of viewing database items in the application

### ISSUE THREAD

**Issue by savursool247** [ErrolKeith/CornerTeam#15]
How should the searches be viewed in the SearchEngine panel and the Admin panel.

**Comment by ErrolKeith** [comment]
I say do the same thing as the JList on the admin panel.

We can use one panel to display the information and the information displayed will be tied to a select statement from the database with the correct operation modifier. Essentially three strings for the search of the database that will be constants, then we use the same add JList method as our admin panel to display the search to the user. We can clear the JList every time the search button is selected.
