### ISSUE TITLE
P4 APP.REQ - Index of DB items must be read when application starts

### ISSUE THREAD

**Issue by savursool247** [ErrolKeith/CornerTeam#17]
"The inverted index can be stored in one or more file(s) or database tables, 
and that should be read whenever your application starts. "

**Comment by savursool247** [comment]
@ErrolKeith do we only have to write methods for this?

**Comment by ErrolKeith** [comment]
we can use the same method that populates all the files for our admin view. We just need to pull it out of the main and turn that portion of code into a method since the code is already done.

**Comment by ErrolKeith** [comment]
created rebuildIndex method that checks if the file exists on the sytem, if not it deletes the file and notifies the user a file no longer exists and was deleted.
It also checks if the file has been modified, if it has it rebuilds the index and notifies the user the index has been updated.
