### ISSUE TITLE
P4 - Implement a method call for updating file stats on Start-Up

### ISSUE THREAD

**Issue by savursool247** [ErrolKeith/CornerTeam#25]

**Comment by ErrolKeith** [comment]
The only thing i can think of that we would need to update on startup would be the inverted index, which shouldn't be until project 5. What other file stats do you want to be updated on startup?

**Comment by ErrolKeith** [comment]
rebuildIndex() solves this issue. the end of this method will rebuild the index based on the file names and paths in the database
