### ISSUE TITLE
P4 - Work on entry validation to avoid errors and duplicates

### ISSUE THREAD

**Issue by savursool247** [ErrolKeith/CornerTeam#30]
Need to add checks and try-catches to avoid things like duplicate entries, removal of non existent items, and other things like that

**Comment by ErrolKeith** [comment]
added if statement to prevent adding a file that is already in the list, the remove statement also removes any files from the list when it is removed from the database. This handles the duplicates issue. I don't see any input errors beyond that other than the user selecting a non-.txt file. Need to discuss with the group on how we want to handle this. regular expression?

**Comment by ErrolKeith** [comment]
added FileNameExtensionChooser to JFileChooser so the user can only open folders and select .txt extensions
